# 配置文件
# cookie 以实际获取为准，如遇到带双引号的需用 \ 转义，或改为单引号，或将最外层双引号改为单引号
# e.g.1 cookie = "xxx; app_param={\"brand\":\"iPhone\"}"
# e.g.2 cookie = "xxx; app_param={'brand':'iPhone'}"
# e.g.3 cookie = 'xxx; app_param={"brand":"iPhone"}'

# 爱企查e卡监控
ECARDCHECK = true

# 天气预报
CITY = ["上海", "北京"]

# 爱企查【WEB】
# https://www.baidu.com，同百度贴吧 cookie 一样
# 批量查询任务需手动抓包查询之后的 exportkey，可不填
[[AQC]]
cookie = 'log_guid=xxxxxx; BDPPN=xxx"xxx;...'
exportkey = ""
reuid = ""

# 翼云盘
# https://cloud.189.cn/web/login.html
[[CLOUD189]]
password = "Sitoi"
phone = "18888xxxxxx"

# CSDN【WEB】
# https://www.csdn.net cookie
[[CSDN]]
cookie = "uuid_tt_dd=xxxxxx; _ga=xxxxxx; UserName=xxxxxx; UserInfo=xxxxxx; UserToken=xxxxxx; UserNick=xxxxxx; AU=768; UN=xxxxxx; BT=xxxxxx; p_uid=xxxxxx; Hm_up_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_ct_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx dc_sid=xxxxxx; c_segment=xxxxxx; dc_session_id=xxxxxx; csrfToken=xxxxxx; c_first_ref=xxxxxx; c_first_page=xxxxxx; c_page_id=xxxxxx; announcement-new=xxxxxx; log_Id_click=xxxxxx; c_pref=xxxxxx; c_ref=xxxxxx; dc_tos=xxxxxx; log_Id_pv=xxxxxx; log_Id_view=xxxxxx"

# 恩山论坛【WEB】
# https://www.right.com.cn/forum/forum.php cookie
[[ENSHAN]]
cookie = "DJyZ_2132_saltkey=xxxxxx; DJyZ_2132_lastvisit=xxxxxx; DJyZ_2132_onlineusernum=xxxx; DJyZ_2132_sendmail=1; DJyZ_2132_ulastactivity=xxxxxx; DJyZ_2132_auth=xxxxxxxx; DJyZ_2132_sid=0; DJyZ_2132_connect_is_bind=0; DJyZ_2132_nofavfid=1; DJyZ_2132_checkpm=1; DJyZ_2132_noticeTitle=1; DJyZ_2132_lastact=xxxxxx"

# Freenom【WEB】
# https://www.freenom.com
[[FREENOM]]
password = ""
username = ""

# HOSTLOC【WEB】
# https://hostloc.com
[[HOSTLOC]]
password = ""
username = ""

# 爱奇艺【WEB】
# https://www.iqiyi.com cookie
[[IQIYI]]
cookie = "__dfp=xxxxxx; QP0013=xxxxxx; QP0022=xxxxxx; QYABEX=xxxxxx; P00001=xxxxxx; P00002=xxxxxx; P00003=xxxxxx; P00007=xxxxxx; QC163=xxxxxx; QC175=xxxxxx; QC179=xxxxxx; QC170=xxxxxx; P00010=xxxxxx; P00PRU=xxxxxx; P01010=xxxxxx; QC173=xxxxxx; QC180=xxxxxx; P00004=xxxxxx; QP0030=xxxxxx; QC006=xxxxxx; QC007=xxxxxx; QC008=xxxxxx; QC010=xxxxxx; nu=xxxxxx; __uuid=xxxxxx; QC005=xxxxxx;"

# 无忧行【APP】
# 打开app-我的-任务中心 很多链接都有token 格式应该是32位16进制数
[[JEGOTRIP]]
token = ""

# 掘金【WEB】
# https://juejin.cn cookie
[[JUEJIN]]
cookie = "ttcid=xxxxxx; MONITOR_WEB_ID=xxxxxx; passport_csrf_token_default=xxxxxx; passport_csrf_token=xxxxxx; s_v_web_id=xxxxxx; MONITOR_DEVICE_ID=xxxxxx; n_mh=xxxxxx; passport_auth_status=xxxxxx; passport_auth_status_ss=xxxxxx; sid_guard=xxxxxx; uid_tt=xxxxxx; uid_tt_ss=xxxxxx; sid_tt=xxxxxx; sessionid=xxxxxx; sessionid_ss=xxxxxx; sid_ucp_v1=xxxxxx; ssid_ucp_v1=xxxxxx; odin_tt=xxxxxx; tt_scid=xxxxxx"

# 芒果TV【WEB】
# https://www.mgtv.com 请求参数
[[MGTV]]
params = "uuid=xxxxxx&uid=xxxxxx&ticket=xxxxxx&token=xxxxxx&device=iPhone&did=xxxxxx&deviceId=xxxxxx&appVersion=6.8.2&osType=ios&platform=iphone&abroad=0&aid=xxxxxx&nonce=xxxxxx×tamp=xxxxxx&appid=xxxxxx&type=1&sign=xxxxxx&callback=xxxxxx"

# 小米运动【APP】
# 最大步数
# 最小步数
# 小米运动 APP 密码
# 小米运动 APP 手机号
[[MIMOTION]]
max_step = "20000"
min_step = "10000"
password = "Sitoi"
phone = "18888xxxxxx"

# NGA【APP】
# https://ngabbs.com/nuke.php POST 请求主体 access_token
# https://ngabbs.com/nuke.php POST 请求主体 access_uid，纯数字
[[NGA]]
token = "X8xxxxghxxxxxxxxujxxxxxxxv9xxxxxxxxccxxx"
uid = "xxxxx391"

# 吾爱破解【WEB】
# https://www.52pojie.cn cookie
[[POJIE]]
cookie = "htVD_2132_client_token=xxxxxx; htVD_2132_connect_is_bind=xxxxxx; htVD_2132_connect_uin=xxxxxx; htVD_2132_nofavfid=xxxxxx; htVD_2132_smile=xxxxxx; Hm_lvt_46d556462595ed05e05f009cdafff31a=xxxxxx; htVD_2132_saltkey=xxxxxx; htVD_2132_lastvisit=xxxxxx; htVD_2132_client_created=xxxxxx; htVD_2132_auth=xxxxxx; htVD_2132_connect_login=xxxxxx; htVD_2132_home_diymode=xxxxxx; htVD_2132_visitedfid=xxxxxx; htVD_2132_viewid=xxxxxx; KF4=xxxxxx; htVD_2132_st_p=xxxxxx; htVD_2132_lastcheckfeed=xxxxxx; htVD_2132_sid=xxxxxx; htVD_2132_ulastactivity=xxxxxx; htVD_2132_noticeTitle=xxxxxx;"

# 什么值得买
# https://www.smzdm.com cookie
[[SMZDM]]
cookie = "sess=xxxxxx;"

# 联通营业厅【APP】
# 联通营业厅 APP 抓包域名为 https://m.client.10010.com/mobileService/login.htm 请求内容的 appId
# 联通营业厅 APP 手机号
# 联通营业厅 APP 密码
[[UNICOM]]
app_id = ""
mobile = "18888xxxxxx"
password = ""

# V2EX【WEB】
# https://v2ex.com，注意要抓签到那次的 ck（相当于需要先手动浏览器签到一次），不然可能签到无效
# 使用代理信息，无密码示例：http://127.0.0.1:1080 有密码示例：http://username:password@127.0.0.1:1080
[[V2EX]]
cookie = "_ga=xxxxxx; __cfduid=xxxxxx; PB3_SESSION=xxxxxx; A2=xxxxxx; V2EXSETTINGS=xxxxxx; V2EX_REFERRER=xxxxxx; V2EX_LANG=xxxxxx; _gid=xxxxxx; V2EX_TAB=xxxxxx;"
proxy = ""

# 腾讯视频【WEB】
# https://v.qq.com 搜索带有 auth_refresh 的 url，填写其完整的 URL
# https://v.qq.com 搜索带有 auth_refresh 的 url，填写其完整的 URL
[[VQQ]]
auth_refresh = "https://access.video.qq.com/user/auth_refresh?vappid=xxxxxx&vsecret=xxxxxx&type=qq&g_tk=&g_vstk=xxxxxx&g_actk=xxxxxx&callback=xxxxxx&_=xxxxxx"
cookie = "pgv_pvid=xxxxxx; pac_uid=xxxxxx; RK=xxxxxx; ptcz=xxxxxx; tvfe_boss_uuid=xxxxxx; video_guid=xxxxxx; video_platform=xxxxxx; pgv_info=xxxxxx; main_login=xxxxxx; vqq_access_token=xxxxxx; vqq_appid=xxxxxx; vqq_openid=xxxxxx; vqq_vuserid=xxxxxx; vqq_refresh_token=xxxxxx; login_time_init=xxxxxx; uid=xxxxxx; vqq_vusession=xxxxxx; vqq_next_refresh_time=xxxxxx; vqq_login_time_init=xxxxxx; login_time_last=xxxxxx;"

# 联通沃邮箱【公众号】
# 密码
# true 为开启21天自动暂停，false 为关闭自动暂停、每天都签到，默认开启自动暂停
# 手机号
# 联通沃邮箱公众号 https://nyan.mail.wo.cn/cn/sign/index/index?mobile 开头的 URL
[[WOMAIL]]
password = "Sitoi"
pause21days = true
phone = "18888xxxxxx"
url = "https://nyan.mail.wo.cn/cn/sign/index/index?mobile=xxxxxx&userName=&openId=xxxxxx"

# 科技玩家签到【web】
[[KJWJ]]
username = "xxx@163.com"
password = "xxx"

# 数码之家【WEB】
[[MYDIGIT]]
cookie = "xxx"

# 小蚁【IOS】
[[XIAOYI]]
token = ""
token_secret = ""
userid = ""

# 滴滴【IOS】
[[DIDI]]
token = ""

# 和彩云【IOS】
[[MCLOUD]]
Authorization = 'Basic xxxx注意有空格'
phoneNumber = "13xx"

# 顺丰【IOS】
[[SFEXPRESS]]
jsbundle = "d25cxx"
deviceId = "F91EE4-xxx"
memNo = "00000000000000000000xxxx"

# WPS【WEB】
# https://www.kdocs.cn cookie
[[WPS]]
cookie = ""

# smxdiy【WEB】
[[SMXDIY]]
cookie = ""

# 建行生活【IOS】
[[CCB_LIFE]]
skey = ""
body = ''

# 看雪论坛【WEB】
[[KANXUE]]
cookie = ""
